_wandb:
    value:
        cli_version: 0.23.1
        e:
            fhomtvcnj9r0dm71o3masptunrncq2x1:
                args:
                    - --env_name
                    - cube-single-play-singletask-v0
                    - --wm_ckpt
                    - checkpoints_cube_single_play_v0/checkpoint_20000.npz
                codePath: drqv2_world_model.py
                codePathLocal: drqv2_world_model.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "254179012608"
                        used: "235935813632"
                email: danielzhu501@gmail.com
                executable: C:\Users\danie_gfshjqx\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: a3c6082713984d61cd2e35881377de7ba4d75574
                    remote: https://github.com/Daniel-1-2-3/SAC-with-Action-Chunks-and-World-Model
                host: Daniel
                memory:
                    total: "8155979776"
                os: Windows-11-10.0.26200-SP0
                program: C:\Daniel\High School\Research\SAC_Action_Chunks_World_Model\drqv2_world_model.py
                python: CPython 3.12.5
                root: C:\Daniel\High School\Research\SAC_Action_Chunks_World_Model
                startedAt: "2026-07-08T17:20:42.425609Z"
                writerId: fhomtvcnj9r0dm71o3masptunrncq2x1
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 12
                - 105
            "2":
                - 1
                - 12
                - 105
            "3":
                - 16
                - 61
            "4": 3.12.5
            "5": 0.23.1
            "8":
                - 2
                - 3
            "12": 0.23.1
            "13": windows-amd64
action_key:
    value: action
critic_target_tau:
    value: 0.01
env_name:
    value: cube-single-play-singletask-v0
feature_dim:
    value: 50
gamma:
    value: 0.99
hidden_dim:
    value: 1024
horizon:
    value: 15
imagination_batch:
    value: 2048
lr:
    value: 0.0001
num_train_steps:
    value: 100000
obs_key:
    value: state
presets:
    value: null
seed:
    value: 0
seq_len_seed:
    value: 64
stddev_clip:
    value: 0.3
stddev_schedule:
    value: linear(1.0,0.1,100000)
wm_ckpt:
    value: checkpoints_cube_single_play_v0/checkpoint_20000.npz
